# Generated by Django 2.2.2 on 2019-12-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_socio',
            name='email',
            field=models.CharField(blank=True, default='noid', max_length=100),
        ),
    ]
